config/routes.rb
Rails.application.routes.draw do
  get 'posts/all_posts'
  resources :likes
  resources :posts do
    resources :likes
  end
  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy

    validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :likes, dependent: :destroy

  validates :email, :username, :name, :password, presence: true

  validates :email, uniqueness: true
  validates :username, uniqueness: true

  validates :name, :username, length: {
    minimum: 3,
    #customize the error message. The %{count}, rails provide it to us from the minimum
    too_short: "must have at least %{count} letters"
}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post, only: [:show, :update, :destroy, :create]
  before_action :find_like, only: [:destroy]

  def index
    @posts = []
    @likes = current_user.likes
     @likes.each do |l| 
      @posts.push(Post.find(l.post_id))
       end 
  end

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to request.referrer
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to request.referrer
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_like
    @like = @post.likes.find(params[:id])
 end

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :all_posts, :new, :create, :show, :edit, :update, :delete, :destroy]
  before_action :set_post, only: [:show]
  before_action :set_post_private, only: [:edit, :update, :delete, :destroy]
  
  def index
    @posts = current_user.posts
  end

  def all_posts
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        # format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def delete
  end

  def update
    @post.update(post_params)
      
    redirect_to @post
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end


  private
  
  def set_post
    @post = Post.find(params[:id])
  end

  def set_post_private
    @post = current_user.posts.find_by(id: params[:id])
    if @post  
    else
      respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Not Allowed' }
      end
    end 
  end

  def post_params
    params.require(:post).permit(:image, :caption, :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div>
<%= image_tag("logo.png", class: 'image-responsive', size: "23x23") %>
<strong class="navbar-brand">MOMENT</strong>
</div>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
    
     <li class="nav-item active">
         <%= link_to("My Profile", posts_path, class: 'nav-link') %>
     </li>

     <li class="nav-item active">
         <%= link_to("All Posts", posts_all_posts_path, class: 'nav-link') %>
      </li>
    
      <li class="nav-item active">
         <%= link_to("Log Out", destroy_user_session_path, method: :delete, class: 'nav-link') %>
      </li>
     
<% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/likes/index.html.erb
<main role="main">

<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading"><%= current_user.name %>'s Likes</h1>
    </div>
</section>


<div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
       <% @posts.each do |post| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
           <%= image_tag(post.image, width: "100%", height: "300", class: "card-img-top") %>
                <div class="card-body">
              
                <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
                    <% if pre_like %>
                      <%= link_to(image_tag("like.png", class: 'image-responsive', size: "30x30"), post_like_path(post, pre_like), method: :delete) %>
                    <% else %>
                     <%= link_to(image_tag("unlike.png", class: 'image-responsive', size: "30x30"), post_likes_path(post), method: :post) %>
                    <% end %>
                    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

                  <p class="card-text"><strong class="card-title"><%= link_to post.user.username %> </strong><%= post.caption %></p>
                    <div class="d-flex justify-content-between align-items-center">
                         <div class="btn-group"></div>
                        <small class="text-muted"><%= time_ago_in_words(post.created_at) %></small>
                    </div>
                </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  </main>

app/views/posts/_form.html.erb
<div class="container-fluid">
  <div class="row no-gutter">
  <%= image_tag("background2.jpg", class: "d-none d-md-flex col-md-4 col-lg-6 image-responsive") %>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
            <h3 class="login-heading mb-4">Manage Post</h3>
                    <%= form_with(model: @post, local: true) do |form| %>
                      <% if @post.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

                          <ul>
                          <% @post.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                        </div>
                      <% end %>

                      <div class="form-label-group">
                        <%= form.text_field :image, autofocus: true, autocomplete: "url", placeholder: "Image url", class: "form-control",  id: "inputImage" %>
                        <label for="inputImage">Image</label>
                      </div>

                      <div class="form-label-group">
                        <%= form.text_field :caption, autocomplete: "current-caption", placeholder: "caption", class: "form-control",  id: "inputCaption" %>
                        <label for="inputCaption">Caption</label>
                      </div>

                      <div class="actions">
                        <%= form.submit class: "btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" %>
                      </div>
                    <% end %>
                    <div class="text-center"><br/>
                    <%= link_to 'Back', posts_path %>
                    </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/all_posts.html.erb
<main role="main">

<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">All Posts</h1>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
       <% @posts.each do |post| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <%= image_tag(post.image, width: "100%", height: "300", class: "card-img-top") %>
                <div class="card-body">
                  
                    <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
                    <% if pre_like %>
                      <%= link_to(image_tag("like.png", class: 'image-responsive', size: "30x30"), post_like_path(post, pre_like), method: :delete) %>
                    <% else %>
                     <%= link_to(image_tag("unlike.png", class: 'image-responsive', size: "30x30"), post_likes_path(post), method: :post) %>
                    <% end %>
                    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

                  <p class="card-text"><strong class="card-title"><%= link_to post.user.username %> </strong><%= post.caption %></p>

                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group"></div>
                        <small class="text-muted"><%= time_ago_in_words(post.created_at) %></small>
                    </div>
                </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  </main>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<main role="main">

<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading"><%= current_user.name %>'s Profile</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <%= link_to 'Add Post', new_post_path,  class: 'btn btn-primary my-2' %>
        <%= link_to 'View Likes', likes_path,  class: 'btn btn-secondary my-2' %>
    </div>
  </section>


  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
       <% @posts.each do |post| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <%= image_tag(post.image, width: "100%", height: "300", class: "card-img-top") %>
                <div class="card-body">
                    
                    <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
                    <% if pre_like %>
                      <%= link_to(image_tag("like.png", class: 'image-responsive', size: "30x30"), post_like_path(post, pre_like), method: :delete) %>
                    <% else %>
                     <%= link_to(image_tag("unlike.png", class: 'image-responsive', size: "30x30"), post_likes_path(post), method: :post) %>
                    <% end %>
                    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

                  
                  <p class="card-text"><strong class="card-title"><%= link_to post.user.username %> </strong><%= post.caption %></p>
                    
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                          <%= link_to 'View', post, class: 'btn btn-sm btn-outline-secondary' %>
                          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-sm btn-outline-secondary' %>
                          <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-secondary' %>

                        </div>
                        <small class="text-muted"><%= time_ago_in_words(post.created_at) %></small>
                    </div>
                </div>
          </div>
        </div>

        <% end %>
      </div>
    </div>
  </div>

  </main>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
           <%= image_tag(@post.image, width: "100%", height: "300", class: "card-img-top") %>
                <div class="card-body">
                    
              <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
                    <% if pre_like %>
                      <%= link_to(image_tag("like.png", class: 'image-responsive', size: "30x30"), post_like_path(@post, pre_like), method: :delete) %>
                    <% else %>
                     <%= link_to(image_tag("unlike.png", class: 'image-responsive', size: "30x30"), post_likes_path(@post), method: :post) %>
                    <% end %>
                    <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

                  <p class="card-text"><strong class="card-title"><%= link_to @post.user.username %> </strong><%= @post.caption %></p>
                </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<p>Welcome <%= @name %> </p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>